id: I27371D02
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 17:58:35.850438+00:00
last_modified: 2022-12-14 17:58:35.850443+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-005
  eft-text-version: 1.1.5 2020
  title: Toh_271-The_Eight_Buddhas-v2
bases:
  E17D:
    source_metadata: null
    order: 1
    base_file: E17D.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
